name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🌱 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: '🚀 Optimization'
    labels:
      - 'perf'
      - 'opt'
      - 'refactor'
      - 'Optimization'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'docs'
exclude-labels:
  - 'no'
  - 'wontfix'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's Changed

  $CHANGES
